version: '3.6'

services:
  web:
    environment:
      - TYPO3_CONTEXT=Development
      - typo3DatabaseName=db
      - typo3DatabasePassword=root
      - typo3DatabaseHost=db
      - typo3DatabaseUsername=root
